# Generated by Django 5.1.7 on 2025-03-28 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(model_name="task", old_name="title", new_name="name",),
        migrations.RemoveField(model_name="task", name="estimated_hours",),
        migrations.RemoveField(model_name="task", name="max_continuous_hours",),
        migrations.AddField(
            model_name="task",
            name="estimated_minutes",
            field=models.IntegerField(default=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="task",
            name="max_consecutive_minutes",
            field=models.IntegerField(default=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="task",
            name="start_preference",
            field=models.CharField(
                choices=[
                    ("ASAP", "As soon as possible"),
                    ("ALAP", "As late as possible"),
                ],
                default="ASAP",
                max_length=4,
            ),
        ),
        migrations.AlterField(
            model_name="task", name="deadline", field=models.DateField(),
        ),
        migrations.CreateModel(
            name="ScheduleAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("event_name", models.CharField(max_length=200)),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scheduler.task",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(name="Schedule",),
    ]
