# Generated by Django 5.1.7 on 2025-03-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "scheduler",
            "0002_rename_title_task_name_remove_task_estimated_hours_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="start_preference",
            field=models.CharField(
                choices=[("ASAP", "ASAP"), ("ALAP", "ALAP")],
                default="ASAP",
                max_length=4,
            ),
        ),
    ]
