# Generated by Django 5.1.7 on 2025-03-29 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0004_weeklytimerange"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="weeklytimerange", unique_together=set(),),
        migrations.AddField(
            model_name="task",
            name="meeting_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("Task", "Task"),
                    ("Weekly Activity", "Weekly Activity"),
                    ("Meeting", "Meeting"),
                ],
                default="Task",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="scheduleassignment",
            name="event_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="scheduleassignment",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="scheduler.task"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="estimated_minutes",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="max_consecutive_minutes",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task", name="name", field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="task",
            name="start_preference",
            field=models.CharField(
                choices=[("ASAP", "ASAP"), ("ALAP", "ALAP")],
                default="ASAP",
                max_length=10,
            ),
        ),
    ]
