# Generated by Django 5.1.7 on 2025-03-29 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0005_alter_weeklytimerange_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="task", name="estimated_minutes",),
        migrations.RemoveField(model_name="task", name="max_consecutive_minutes",),
        migrations.RemoveField(model_name="task", name="start_preference",),
        migrations.AddField(
            model_name="task",
            name="weekly_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="weekly_end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="weekly_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="weekly_start_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task", name="name", field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="task",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("TASK", "Task"),
                    ("WEEKLY", "Weekly Activity"),
                    ("MEETING", "Meeting"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="weeklytimerange",
            name="end_hour",
            field=models.IntegerField(default=19),
        ),
        migrations.AlterField(
            model_name="weeklytimerange",
            name="start_hour",
            field=models.IntegerField(default=10),
        ),
    ]
