# Generated by Django 5.1.7 on 2025-03-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0006_remove_task_estimated_minutes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="weekly_day",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MON", "Lunes"),
                    ("TUE", "Martes"),
                    ("WED", "Miércoles"),
                    ("THU", "Jueves"),
                    ("FRI", "Viernes"),
                    ("SAT", "Sábado"),
                    ("SUN", "Domingo"),
                ],
                max_length=3,
                null=True,
            ),
        ),
    ]
