# Generated by Django 5.1.7 on 2025-03-30 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0007_task_weekly_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="estimated_minutes",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="max_consecutive_minutes",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="start_preference",
            field=models.CharField(
                blank=True,
                choices=[("ASAP", "ASAP"), ("ALAP", "ALAP")],
                max_length=4,
                null=True,
            ),
        ),
    ]
