# Generated by Django 5.1.7 on 2025-03-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "scheduler",
            "0008_task_estimated_minutes_task_max_consecutive_minutes_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="meeting_end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task", name="name", field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="task",
            name="weekly_day",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
