# Generated by Django 5.1.7 on 2025-03-31 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0009_task_meeting_end_time_alter_task_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="weeklytimerange",
            name="active_days",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="weeklytimerange", name="end_hour", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="weeklytimerange",
            name="start_hour",
            field=models.IntegerField(),
        ),
    ]
