# Generated by Django 5.1.7 on 2025-03-31 10:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0010_weeklytimerange_active_days_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="weeklytimerange",
            name="end_hour",
            field=models.IntegerField(default=19),
        ),
        migrations.AlterField(
            model_name="weeklytimerange",
            name="start_hour",
            field=models.IntegerField(default=10),
        ),
        migrations.AlterUniqueTogether(
            name="weeklytimerange", unique_together={("user", "week_start")},
        ),
    ]
