# Generated by Django 5.1.7 on 2025-03-31 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0011_alter_weeklytimerange_end_hour_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheduleassignment",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="scheduler.task",
            ),
        ),
    ]
