# Generated by Django 5.1.7 on 2025-04-02 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0012_alter_scheduleassignment_task"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="max_consecutive_minutes",
            new_name="max_daily_minutes",
        ),
    ]
