# Generated by Django 5.1.7 on 2025-04-03 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0013_rename_max_consecutive_minutes_task_max_daily_minutes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportedTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("canvas_id", models.BigIntegerField(unique=True)),
                ("course_id", models.BigIntegerField()),
                ("name", models.CharField(max_length=255)),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                ("reviewed", models.BooleanField(default=False)),
                ("estimated_minutes", models.IntegerField(blank=True, null=True)),
                ("max_daily_minutes", models.IntegerField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
