# Generated by Django 5.1.7 on 2025-04-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0014_importedtask"),
    ]

    operations = [
        migrations.AddField(
            model_name="importedtask",
            name="course_name",
            field=models.CharField(default="Sin Curso", max_length=255),
            preserve_default=False,
        ),
    ]
