# Generated by Django 5.1.7 on 2025-04-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0015_importedtask_course_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importedtask",
            name="course_name",
            field=models.CharField(default="Curso sin nombre", max_length=255),
        ),
    ]
