# Generated by Django 5.1.7 on 2025-04-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0017_alter_importedtask_course_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="ignored_by_meeting",
            field=models.BooleanField(default=False),
        ),
    ]
