# Generated by Django 5.1.7 on 2025-04-10 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0018_task_ignored_by_meeting"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IgnoredWeeklyInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "weekly_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="scheduler.task"
                    ),
                ),
            ],
            options={"unique_together": {("user", "weekly_task", "date")},},
        ),
    ]
