# Generated by Django 5.1.7 on 2025-07-08 12:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0021_canvasprofile_canvas_course_ids"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="importedtask", unique_together={("canvas_id", "user")},
        ),
    ]
