# Generated by Django 5.1.7 on 2025-07-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0022_alter_importedtask_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importedtask", name="canvas_id", field=models.BigIntegerField(),
        ),
    ]
